baseURL = "http://localhost:1313/"
languageCode = "FR-fr"
title = "Lingerie"

theme = "txstore"

[outputs]
home = ["html"]
section = ["json","html"]
page = ["json","html"]

[params]
api_url = "https://DB9NGVV9D8ZK0UJNJP4GA9R5HX0XT4VT@www.drop-sexy.com/api/"
api_categories ="categories/"
api_product ="products/"
